"""
Report generator: converts staleness scores and risk exposure into
structured remediation plans and formatted reports.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from typing import Any

import yaml

from src.scorer import StalenessScore
from src.risk_simulator import RiskExposure, PortfolioRisk


# ---------------------------------------------------------------------------
# Remediation plan
# ---------------------------------------------------------------------------

@dataclass
class RemediationPlan:
    """Ready-to-act remediation plan for a single stale entity."""
    entity: str
    domain: str
    staleness_level: str
    primary_action: str
    effort_level: str           # LOW | MEDIUM | HIGH
    estimated_hours: int
    code_snippet: str
    explanation: str
    priority: int               # 1 = highest


# ---------------------------------------------------------------------------
# Code snippet templates
# ---------------------------------------------------------------------------

_RAG_OVERRIDE_TEMPLATE = '''\
# RAG override for {entity} ({domain})
# Generated by DKSM — replace stale model belief at inference time

SYSTEM_PATCH = """
[DATA CURRENCY NOTICE — INJECTED BY DKSM]
The following value was updated on {effective_date} and supersedes any
prior knowledge the model may have:

  {domain} / {entity}: {warehouse_value}

Use ONLY this value when answering questions about {entity}.
"""

def build_prompt_with_patch(user_question: str) -> str:
    return SYSTEM_PATCH + "\\n\\n" + user_question
'''

_FINE_TUNE_TEMPLATE = '''\
# Fine-tuning data point for {entity} ({domain})
# Add to your supervised fine-tuning dataset

training_example = {{
    "messages": [
        {{
            "role": "user",
            "content": "What is the current {entity} threshold/value?"
        }},
        {{
            "role": "assistant",
            "content": "As of {effective_date}, the current {entity} is {warehouse_value}."
        }}
    ]
}}
'''

_MONITORING_ALERT_TEMPLATE = '''\
# Staleness monitoring alert rule for {entity}
# Add to your observability pipeline

alert_rule = {{
    "name": "dksm_{domain}_{entity_slug}_staleness",
    "condition": "staleness_score > 0.7",
    "domain": "{domain}",
    "entity": "{entity}",
    "last_known_value": "{warehouse_value}",
    "effective_date": "{effective_date}",
    "action": "trigger_rag_override",
    "notify_slack_channel": "#data-freshness-alerts"
}}
'''


def _slugify(name: str) -> str:
    return name.lower().replace(" ", "_").replace("-", "_")


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

class ReportGenerator:
    """
    Generates remediation plans and structured reports from staleness scores.
    """

    def __init__(self, config_path: str = "config/domains.yaml") -> None:
        with open(config_path) as f:
            self.config = yaml.safe_load(f)

    def generate_remediation_plan(
        self,
        score: StalenessScore,
        warehouse_value: str = "",
        effective_date: str = "",
    ) -> RemediationPlan:
        """Generate a remediation plan for a single stale entity."""
        level = score.staleness_level
        entity = score.entity
        domain = score.domain
        wv = warehouse_value or score.warehouse_truth
        ed = effective_date or score.effective_date

        if level == "CRITICAL":
            action = "IMMEDIATE: Inject RAG system-prompt patch before any model inference"
            effort = "LOW"
            hours = 2
            snippet = _RAG_OVERRIDE_TEMPLATE.format(
                entity=entity, domain=domain,
                effective_date=ed, warehouse_value=wv,
            )
            explanation = (
                f"{entity} is critically stale (score: {score.staleness_score:.2f}). "
                f"The model believes '{score.model_belief}' but the Gold layer says '{wv}'. "
                "Inject the warehouse value as a system-prompt patch immediately to prevent "
                "wrong decisions. Schedule fine-tuning within 30 days."
            )
            priority = 1

        elif level == "STALE":
            action = "SOON: Add to next fine-tuning batch or RAG retrieval augmentation"
            effort = "MEDIUM"
            hours = 8
            snippet = _FINE_TUNE_TEMPLATE.format(
                entity=entity, domain=domain,
                effective_date=ed, warehouse_value=wv,
            )
            explanation = (
                f"{entity} has drifted (score: {score.staleness_score:.2f}). "
                "Add a corrective training example to the next fine-tuning run, "
                "or wire up a RAG retrieval step that always fetches the current value "
                "from the Gold layer before answering questions in this domain."
            )
            priority = 2

        else:
            action = "MONITOR: Set up automated staleness alerts"
            effort = "LOW"
            hours = 1
            snippet = _MONITORING_ALERT_TEMPLATE.format(
                entity=entity, domain=domain,
                effective_date=ed, warehouse_value=wv,
                entity_slug=_slugify(entity),
            )
            explanation = (
                f"{entity} is currently fresh (score: {score.staleness_score:.2f}). "
                "Set up automated monitoring so DKSM alerts you when this entity's "
                "staleness crosses the warning threshold."
            )
            priority = 3

        return RemediationPlan(
            entity=entity,
            domain=domain,
            staleness_level=level,
            primary_action=action,
            effort_level=effort,
            estimated_hours=hours,
            code_snippet=snippet,
            explanation=explanation,
            priority=priority,
        )

    def generate_domain_report(
        self,
        domain: str,
        scores: list[StalenessScore],
        portfolio_risk: PortfolioRisk,
        include_code_snippets: bool = True,
    ) -> dict[str, Any]:
        """
        Generate a full domain health report suitable for JSON export or display.
        """
        plans = [
            self.generate_remediation_plan(s)
            for s in scores
            if s.domain == domain
        ]
        plans.sort(key=lambda p: p.priority)

        domain_exposure = portfolio_risk.domain_breakdown.get(domain, 0.0)
        domain_cfg = self.config["domains"].get(domain, {})

        return {
            "report_timestamp": datetime.now(timezone.utc).isoformat(),
            "domain": domain,
            "display_name": domain_cfg.get("display_name", domain),
            "entity_count": len(scores),
            "critical_count": sum(1 for s in scores if s.staleness_level == "CRITICAL"),
            "stale_count": sum(1 for s in scores if s.staleness_level == "STALE"),
            "fresh_count": sum(1 for s in scores if s.staleness_level == "FRESH"),
            "estimated_exposure_usd": domain_exposure,
            "remediation_plans": [
                {
                    "entity": p.entity,
                    "staleness_level": p.staleness_level,
                    "primary_action": p.primary_action,
                    "effort_level": p.effort_level,
                    "estimated_hours": p.estimated_hours,
                    "explanation": p.explanation,
                    **({"code_snippet": p.code_snippet} if include_code_snippets else {}),
                }
                for p in plans
            ],
        }

    def generate_executive_summary(
        self,
        all_scores: list[StalenessScore],
        portfolio_risk: PortfolioRisk,
    ) -> str:
        """Plain-text executive summary suitable for Slack/email."""
        lines = [
            "=== DKSM Domain Knowledge Staleness Report ===",
            f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            f"Portfolio Risk Grade: {portfolio_risk.risk_grade}",
            f"Total Estimated Exposure: ${portfolio_risk.total_exposure_usd:,.0f}",
            f"Decisions at Risk (30d): {portfolio_risk.total_decisions_at_risk:,}",
            "",
            "Domain Breakdown:",
        ]
        for domain, exposure in portfolio_risk.domain_breakdown.items():
            lines.append(f"  {domain}: ${exposure:,.0f}")

        if portfolio_risk.critical_entities:
            lines += ["", "CRITICAL Entities Requiring Immediate Action:"]
            for ent in portfolio_risk.critical_entities:
                lines.append(f"  ⚠  {ent}")

        return "\n".join(lines)
